apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: test
        image: subhashchandra369/testnginx:v2
        ports:
        - containerPort: 80
